Pages still load even if a JSON data file is missing
BirkbeckCTP/consortial_billing pull request #49
Opened 2024-02-19 14:16 UTC by joemull

Fixes #43

2024-02-19 16:16 UTC, ajrbyers approved these changes

2024-02-21 13:52 UTC, mauromsl requested changes
Minor nitpick but otherwise good

2024-02-22 07:54 UTC, joemull commented
> Minor nitpick but otherwise good

I don't see any comments under this--did they not get saved?

2024-02-22 08:49 UTC, mauromsl commented
> > Minor nitpick but otherwise good
> 
> Thanks @mauromsl but I don't see any comments under this--did they not get saved?

yeah odd, it picked the overall comment but not the inline. It is there now

2024-02-27 09:56 UTC, mauromsl approved these changes

2024-02-27 09:56 UTC, merged